name: res
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.6.1

# Add regular dependencies here.
# dependencies:
# path: ^1.8.0

dev_dependencies:
  build_runner: ^2.4.13
  # dart pub global activate flutter_asset_generator
  flutter_asset_generator: ^1.2.0
  # flutter_gen_runner: ^5.8.0

  flutter_lints: ^4.0.0
  intl_utils: ^2.8.5
  test: any

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/images/enemy/
    - assets/images/itens/
    - assets/images/units/Orc/Orc/
    - assets/images/units/dev/
    - assets/images/hex/grid/
    - assets/images/hex/nogrid/
    - assets/images/ui_1/Elements/
    - assets/images/floor_zone/
    - assets/images/textures/
    - assets/audio/music/
    - assets/audio/sfx/
# -------------------------------- int generate ----------------------------------------
flutter_intl:
  enabled: true
#  ------------------------------- Flutter GEN -----------------------------------------

