name: res
description: A starting point for Dart libraries or applications.
version: 1.0.2
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.6.1

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter
# path: ^1.8.0
dev_dependencies:
  build_runner: ^2.4.13
  flutter_gen_runner: ^5.8.0
  res_generator: ^0.1.5
  test: any
  # dart pub global activate flutter_asset_generator
  flutter_asset_generator: ^1.2.0



# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/images/enemy/
    - assets/images/itens/
    - assets/images/units/Orc/Orc/
    - assets/images/units/dev/
    # - assets/images/hex/grid/
    - assets/images/hex/nogrid/
    - assets/images/ui_1/Elements/
    - assets/images/floor_zone/
    - assets/images/textures/
    - assets/audio/music/
    - assets/audio/sfx/
    # - packages/res/assets/audio/music/bg_music.ogg
    # - packages/res/assets/audio/sfx/fire_1.mp3
    # - packages/res/assets/audio/sfx/fire_2.mp3
    # - packages/resources/assets/images/hex/grid/hex_1.png
    # - packages/res/assets/images/hex/grid/
# -------------------------------- int generate ----------------------------------------
flutter_intl:
  enabled: true
#  ------------------------------- Flutter GEN -----------------------------------------

flutter_gen:
  output: lib/generated/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)

  integrations:
    
    flutter_svg: false
    rive: false
    lottie: false

  assets:
    enabled: true
    outputs:
      package_parameter_enabled: true
      class_name: Assets

    # outputs:
      # class_name: Assets
      # package_parameter_enabled: false
      # Assets.imagesChip
      # style: camel-case

      # Assets.images_chip
      # style: snake-case

      # Assets.images.chip (default style)
      style: dot-delimiter

    # exclude:
    # - assets-extern/*
    # - pictures/chip5.jpg
#


